kind: pipeline
type: docker
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pip install pytest
  - pytest
- name: docker build
  image: plugins/docker
  commands:
    - docker build .