language: python
python:
  - 3.6
services:
  - mongodb
  - postgresql
  - neo4j
  - docker
before_install:
  - python --version
  - pip install -r requirements.txt
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  #install:
  # - pip install ".[test]" . # install package + test dependencies
script:
  - pytest # run tests
  - docker build -t tweetbot .
after_success:
  - codecov # submit coverage
  - docker login docker.pkg.github.com -u $USERNAME -password--stdin $TOKEN
  - docker tag tweetbot docker.pkg.github.com/jaimehisao/twitterbot/tweetbot:$TRAVIS_BUILD_NUMBER
  - docker push docker.pkg.github.com/jaimehisao/twitterbot/tweetbot:$TRAVIS_BUILD_NUMBER
  - docker tag tweetbot docker.pkg.github.com/jaimehisao/twitterbot/tweetbot:latest
  - docker push docker.pkg.github.com/jaimehisao/twitterbot/tweetbot:latest
