language: python
python:
  - 3.6
services:
  - mongodb
  - postgresql
  - neo4j
before_install:
  - python --version
  - pip install -r requirements.txt
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  #install:
  # - pip install ".[test]" . # install package + test dependencies
script: pytest # run tests
after_success:
  - codecov # submit coverage
